language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"

branches:
    only:
    - dev

# Command to install dependencies
install: make install

# Command to run tests
script: make test
